using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ComponentDescriptor : MonoBehaviour
{
    public ComponentType type = ComponentType.Unknown;
}

public enum ComponentType
{
    Unknown = 0,
    Clay = 1000,
    WetClay,
    KneadedClay,
    KneadedClay2,
    KneadedClay3,
    Water,

    Handle1 = 2000,
    Handle2,
    Handle3,
 
    BlackRocks = 3000,
    BlackRocksGravel,
    RedRocks,
    RedRocksGravel,
    BlackSlip,
    RedSlip,
    ClaySlip,

    PlateRaw =4000,
    PlateRawRed,
    PlateRawBlack,
    Plate1HandleRaw,
    Plate1HandleRawRed,
    Plate1HandleRawBlack,
    Plate2HandleRaw,
    Plate2HandleRawRed,
    Plate2HandleRawBlack,
    MediumVaseRaw,
    MediumVaseRawRed,
    MediumVaseRawBlack,
    MediumVase1HandleRaw,
    MediumVase1HandleRawRed,
    MediumVase1HandleRawBlack,
    MediumVase2HandleRaw,
    MediumVase2HandleRawRed,
    MediumVase2HandleRawBlack,
    MediumVase3HandleRaw,
    MediumVase3HandleRawRed,
    MediumVase3HandleRawBlack,
    BigVaseRaw,
    BigVaseRawRed,
    BigVaseRawBlack,
    BigVase1HandleRaw,
    BigVase1HandleRawRed,
    BigVase1HandleRawBlack,
    BigVase2HandleRaw,
    BigVase2HandleRawRed,
    BigVase2HandleRawBlack,
    BigVase3HandleRaw,
    BigVase3HandleRawRed,
    BigVase3HandleRawBlack,

    PlateBaked = 5000,
    PlateBakedRed,
    PlateBakedBlack,
    Plate1HandleBaked,
    Plate1HandleBakedRed,
    Plate1HandleBakedBlack,
    Plate2HandleBaked,
    Plate2HandleBakedRed,
    Plate2HandleBakedBlack,
    MediumVaseBaked,
    MediumVaseBakedRed,
    MediumVaseBakedBlack,
    MediumVase1HandleBaked,
    MediumVase1HandleBakedRed,
    MediumVase1HandleBakedBlack,
    MediumVase2HandleBaked,
    MediumVase2HandleBakedRed,
    MediumVase2HandleBakedBlack,
    MediumVase3HandleBaked,
    MediumVase3HandleBakedRed,
    MediumVase3HandleBakedBlack,
    BigVaseBaked,
    BigVaseBakedRed,
    BigVaseBakedBlack,
    BigVase1HandleBaked,
    BigVase1HandleBakedRed,
    BigVase1HandleBakedBlack,
    BigVase2HandleBaked,
    BigVase2HandleBakedRed,
    BigVase2HandleBakedBlack,
    BigVase3HandleBaked,
    BigVase3HandleBakedRed,
    BigVase3HandleBakedBlack,
}
